# Generated by Django 5.0.2 on 2024-04-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_tickets', '0006_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='place_media/'),
        ),
    ]
