# Generated by Django 5.0.2 on 2024-04-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_tickets', '0007_alter_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='short_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
